-- DDL REDE SOCIAL
-- CREATE
-- ALTER
-- DROP

CREATE DATABASE db_RedeSocial

USE db_RedeSocial

CREATE TABLE Usuarios(
	Id INT PRIMARY KEY NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Senha VARCHAR(100) NOT NULL,
	Nome VARCHAR(100) NOT NULL
)

CREATE TABLE Postagens(
	Id INT PRIMARY KEY NOT NULL,
	Imagem VARCHAR(100) NULL,
	Legenda VARCHAR(100) NOT NULL,
	Localizacao VARCHAR(100) NULL,
	FK_Usuarios INT NOT NULL,
	FOREIGN KEY (FK_Usuarios) REFERENCES Usuarios (Id)
	)

CREATE TABLE Grupo(
	Id INT PRIMARY KEY NOT NULL,
	Amigos VARCHAR(100) NOT NULL,
	FK_Usuarios INT NOT NULL,
	FOREIGN KEY (FK_Usuarios) REFERENCES Usuarios(Id),
	FK_Postagens INT NOT NULL,
	FOREIGN KEY (FK_Postagens) REFERENCES Postagens(Id)
)

ALTER TABLE Usuarios ADD Foto VARCHAR(100) NULL