-- DDL CLASSIFICADO
-- CREATE
-- ALTER
-- DROP

CREATE DATABASE db_Classificado

USE db_Classificado

CREATE TABLE Clientes(
	Id INT PRIMARY KEY NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Endereço VARCHAR(100) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Senha VARCHAR(100) NOT NULL
)

CREATE TABLE Classificados(
	Id INT PRIMARY KEY NOT NULL,
	Titulo VARCHAR(100) NOT NULL,
	Descricao VARCHAR(100) NOT NULL,
	Valor FLOAT NULL,
	Contato VARCHAR(100) NOT NULL,
	FK_Nome INT NOT NULL,
	FOREIGN KEY (FK_Nome) REFERENCES Clientes (Id)
)

ALTER TABLE Clientes ADD Foto VARCHAR(100) NULL

ALTER TABLE Classificados ADD Foto VARCHAR(100) NULL
